version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
    image: upwork-entry-exam:latest
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5433:5432"
  tests:
    build:
      dockerfile: Dockerfile
    image: upwork-entry-exam:latest
    command: ["pytest", "tests"]
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
  db-migrate:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    image: upwork-entry-exam:latest
    command: "alembic upgrade head"
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
  create-migrations:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    image: upwork-entry-exam:latest
    command: "alembic revision --autogenerate"
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
